<?php if(count($rows)){ $i=1;$total_talked_time_in_second=0;$total_call_count=0;$talked_call_count=0;?>
   <?php foreach($rows AS $row){ ?>
    <?php
    $total_talked_time_in_second=($row->total_talked_time_in_second+$total_talked_time_in_second);
    $total_call_count=($row->total_call_count+$total_call_count);
    $talked_call_count=($row->talked_call_count+$talked_call_count);
    ?>
    <tr scope="row" class="">      
      <td style="text-align:center;"><?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?></td>
      <td style="text-align:center;"><?php echo ($row->total_talked_time_in_second)?gmdate("H:i:s", $row->total_talked_time_in_second):'-'; ?></td>
      <td style="text-align:center;"><?php if($row->total_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="total_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="total_call"><?php echo ($row->total_call_count)?$row->total_call_count:'-'; ?></a></td>
      <td style="text-align:center;"><?php if($row->talked_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="talked_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="talked_call"><?php echo ($row->talked_call_count)?$row->talked_call_count:'-'; ?></a></td>
      <td style="text-align:center;"><?php if($row->not_talked_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="not_talked_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="not_talked_call"><?php echo ($row->not_talked_call_count)?$row->not_talked_call_count:'-'; ?></a></td>
      <td style="text-align:center;"><?php if($row->unique_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="unique_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="unique_call"><?php echo ($row->unique_call_count)?$row->unique_call_count:'-'; ?></a></td>
      <td style="text-align:center;"><?php if($row->outgoing_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="outgoing_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="outgoing_call"><?php echo ($row->outgoing_call_count)?$row->outgoing_call_count:'-'; ?></a></td>      
      <td style="text-align:center;"><?php if($row->incoming_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="incoming_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="incoming_call"><?php echo ($row->incoming_call_count)?$row->incoming_call_count:'-'; ?></a></td>
      <td style="text-align:center;"><?php if($row->missing_opportunities_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="missing_opportunities_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="missing_opportunities_call"><?php echo ($row->missing_opportunities_call_count)?$row->missing_opportunities_call_count:'-'; ?></a></td>
      <td class="auto-show-- hide--" style="text-align:center;"><?php if($row->new_leads_created_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="new_lead_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="new_lead_call"><?php echo ($row->new_leads_created_call_count)?$row->new_leads_created_call_count:'-'; ?></a></td>
      <td class="auto-show-- hide--" style="text-align:center;"><?php if($row->sales_service_call_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="sales_service_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="sales_service_call"><?php echo ($row->sales_service_call_count)?$row->sales_service_call_count:'-'; ?></a></td>
      <td class="auto-show-- hide--" style="text-align:center;"><?php if($row->other_business_count>0){ ?><a href="JavaScript:void(0)" class="download_call_log_details_csv" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="other_business_call"><i class="fa fa-download text-success" aria-hidden="true"></i></a><?php } ?> <a href="JavaScript:void(0);" class="default-link view_details" data-date="<?php echo ($row->call_start)?date_db_format_to_display_format($row->call_start):'-'; ?>" data-type="other_business_call"><?php echo ($row->other_business_count)?$row->other_business_count:'-'; ?></a></td>
	</tr>
    <tr class="spacer"><td colspan="12"></td></tr>
<?php $i++;} ?>
<tr class="spacer"><td colspan="12"></td></tr>
  <tr scope="row" class="">
    <td style="text-align:center;" class="bg-warning">Total</td>
    <td style="text-align:center;" class="bg-warning"><?php echo ($total_talked_time_in_second)?gmdate("H:i:s", $total_talked_time_in_second):'N/A'; ?></td>
    <td style="text-align:center;" class="bg-warning"><?php echo ($total_call_count)?$total_call_count:'N/A';?></td>
    <td style="text-align:center;" colspan="9" class="bg-warning"></td>
  </tr>
  <tr class="spacer"><td colspan="12"></td></tr>
  <tr scope="row" class="">
    <td style="text-align:left;" colspan="4" class="bg-warning"><b>Avg calls per day:</b> <?php echo ($total_call_count)?round(($total_call_count/$i)):'N/A';?></td>
    <td style="text-align:left;" colspan="4" class="bg-warning"><b>Avg Talked calls per day:</b> <?php echo ($talked_call_count)?round(($talked_call_count/$i)):'N/A';?></td>
    <td style="text-align:left;" colspan="4" class="bg-warning"><b>Avg Talked time per day:</b> <?php echo ($total_talked_time_in_second)?gmdate("H:i:s", ($total_talked_time_in_second/$i)):'N/A';?></td>
  </tr>
<?php }else{ ?>
  <tr><td colspan="12" style="text-align:center;">No record found!</td></tr>  
<?php } ?>